// src/views/BetStuff/BetStuffMain.vue
<template>
  <div class="main-section-view">
    <h2>{{ sectionName }}</h2>
    <div class="section-overview">
      <p>Welcome to {{ sectionName }}. Select an option from the navigation to continue.</p>
      
      <div class="quick-access">
        <h3>Quick Access</h3>
        <div class="quick-links">
          <button 
            v-for="sub in subButtons" 
            :key="sub.name"
            @click="navigateTo(sub)"
            class="quick-link-btn bet-stuff-btn"
          >
            {{ sub.name }}
          </button>
        </div>
      </div>
      
      <div class="recent-activity">
        <h3>Recent Activity</h3>
        <div class="activity-stats">
          <div class="stat-card">
            <span class="stat-value">{{ openBetsCount }}</span>
            <span class="stat-label">Open Bets</span>
          </div>
          <div class="stat-card">
            <span class="stat-value">{{ liveBetsCount }}</span>
            <span class="stat-label">Live Bets</span>
          </div>
          <div class="stat-card">
            <span class="stat-value">{{ completedToday }}</span>
            <span class="stat-label">Completed Today</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'
import { useNavigationStore } from '@/stores/navigation'
import { useBetsStore } from '@/stores/bets'
import { useRouter } from 'vue-router'

const navigationStore = useNavigationStore()
const betsStore = useBetsStore()
const router = useRouter()

const sectionName = 'Bet Stuff'

const subButtons = computed(() => {
  const section = navigationStore.navSections.find(s => s.name === sectionName)
  return section ? section.subButtons : []
})

// Mock data - replace with actual store data
const openBetsCount = computed(() => betsStore.openBets?.length || 12)
const liveBetsCount = computed(() => betsStore.liveBets?.length || 5)
const completedToday = ref(3)

function navigateTo(sub) {
  navigationStore.selectSubButton(sectionName, sub)
  const section = navigationStore.navSections.find(s => s.name === sectionName)
  if (section) {
    router.push(`${section.path}/${sub.path}`)
  }
}
</script>

<style scoped>
.main-section-view {
  padding: 1rem;
}

.section-overview {
  background: white;
  border-radius: 12px;
  padding: 2rem;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.quick-access {
  margin-top: 2rem;
}

.quick-access h3 {
  margin-bottom: 1rem;
  color: #333;
}

.quick-links {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 1rem;
}

.quick-link-btn {
  padding: 1.5rem;
  border: none;
  border-radius: 12px;
  font-size: 1.1rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
}

.bet-stuff-btn {
  background: rgba(128, 128, 128, 0.9);
  color: white;
}

.bet-stuff-btn:hover {
  background: #808080;
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
}

.recent-activity {
  margin-top: 2rem;
}

.recent-activity h3 {
  margin-bottom: 1rem;
  color: #333;
}

.activity-stats {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
  gap: 1rem;
}

.stat-card {
  background: #f9f9f9;
  padding: 1.5rem;
  border-radius: 8px;
  text-align: center;
}

.stat-value {
  display: block;
  font-size: 2rem;
  font-weight: bold;
  color: #808080;
}

.stat-label {
  display: block;
  font-size: 0.9rem;
  color: #666;
  margin-top: 0.5rem;
}
</style>

// src/views/BetStuff/BetStuffMain.jsx
import { useNavigate } from 'react-router-dom'
import { useNavigationStore } from '@/store/navigationStore'
import { useBetsStore } from '@/store/betsStore'

function BetStuffMain() {
  const navigate = useNavigate()
  const { navSections, selectSubButton } = useNavigationStore()
  const { getOpenBets, getLiveBets } = useBetsStore()

  const sectionName = 'Bet Stuff'
  const section = navSections.find(s => s.name === sectionName)
  const subButtons = section?.subButtons || []

  const openBetsCount = getOpenBets().length || 12
  const liveBetsCount = getLiveBets().length || 5
  const completedToday = 3

  const navigateTo = (sub) => {
    selectSubButton(sectionName, sub)
    if (section) {
      navigate(`${section.path}/${sub.path}`)
    }
  }

  return (
    <div className="p-4">
      <h2 className="text-2xl font-bold mb-4">{sectionName}</h2>
      <div className="bg-white rounded-xl p-8 shadow-md">
        <p className="text-gray-600 mb-6">
          Welcome to {sectionName}. Select an option from the navigation to continue.
        </p>

        <div className="mt-8">
          <h3 className="text-lg font-semibold mb-4 text-gray-800">Quick Access</h3>
          <div className="grid grid-cols-[repeat(auto-fit,minmax(150px,1fr))] gap-4">
            {subButtons.map((sub) => (
              <button
                key={sub.name}
                onClick={() => navigateTo(sub)}
                className="p-6 border-none rounded-xl text-lg font-semibold cursor-pointer transition-all duration-300 bg-gray-500/90 text-white hover:bg-gray-500 hover:-translate-y-0.5 hover:shadow-lg"
              >
                {sub.name}
              </button>
            ))}
          </div>
        </div>

        <div className="mt-8">
          <h3 className="text-lg font-semibold mb-4 text-gray-800">Recent Activity</h3>
          <div className="grid grid-cols-[repeat(auto-fit,minmax(120px,1fr))] gap-4">
            <div className="bg-gray-100 p-6 rounded-lg text-center">
              <span className="block text-3xl font-bold text-gray-500">{openBetsCount}</span>
              <span className="block text-sm text-gray-600 mt-2">Open Bets</span>
            </div>
            <div className="bg-gray-100 p-6 rounded-lg text-center">
              <span className="block text-3xl font-bold text-gray-500">{liveBetsCount}</span>
              <span className="block text-sm text-gray-600 mt-2">Live Bets</span>
            </div>
            <div className="bg-gray-100 p-6 rounded-lg text-center">
              <span className="block text-3xl font-bold text-gray-500">{completedToday}</span>
              <span className="block text-sm text-gray-600 mt-2">Completed Today</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default BetStuffMain
