// src/views/BetStuff/LiveBetsView.vue
<template>
  <div class="live-bets-view">
    <h2>Live Bets</h2>
    <div v-if="navigationStore.currentFilter" class="filter-info">
      Showing: {{ navigationStore.currentFilter }}
    </div>
    
    <div v-if="betsStore.isLoading" class="loading">
      <LoadingSpinner />
    </div>
    
    <div v-else-if="!filteredBets.length" class="empty-state">
      <p>No live bets at the moment</p>
    </div>
    
    <div v-else class="bets-grid">
      <div v-for="bet in filteredBets" :key="bet.bet_id" class="live-bet-card">
        <div class="live-indicator">
          <span class="pulse"></span>
          LIVE
        </div>
        
        <div class="bet-matchup">
          <div class="team-section">
            <span class="team-name">{{ Object.keys(bet.blue_team)[0] }}</span>
            <span class="team-score">{{ Object.values(bet.blue_team)[0] }}</span>
          </div>
          <div class="vs">VS</div>
          <div class="team-section">
            <span class="team-name">{{ Object.keys(bet.red_team)[0] }}</span>
            <span class="team-score">{{ Object.values(bet.red_team)[0] }}</span>
          </div>
        </div>
        
        <div class="bet-info">
          <div class="info-row">
            <span>Spread:</span>
            <span>{{ bet.spread }}</span>
          </div>
          <div class="info-row">
            <span>Your Position:</span>
            <span class="position">{{ getUserPosition(bet) }}</span>
          </div>
          <div class="info-row">
            <span>Amount:</span>
            <span>${{ getUserAmount(bet) }}</span>
          </div>
        </div>
        
        <div class="bet-participants">
          <h4>Participants</h4>
          <div class="participants-list">
            <div v-for="liveBet in bet.live_bets" :key="liveBet.bettor + liveBet.caller" class="participant">
              <span>{{ liveBet.bettor }} vs {{ liveBet.caller }}</span>
              <span>${{ liveBet.bet_amount }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, onMounted } from 'vue'
import { useNavigationStore } from '@/stores/navigation'
import { useBetsStore } from '@/stores/bets'
import { useUserStore } from '@/stores/user'
import LoadingSpinner from '@/components/common/LoadingSpinner.vue'

const navigationStore = useNavigationStore()
const betsStore = useBetsStore()
const userStore = useUserStore()

const filteredBets = computed(() => {
  const filter = navigationStore.currentFilter
  if (filter === 'Mine') {
    return betsStore.liveBets.filter(bet => 
      bet.live_bets.some(lb => 
        lb.bettor === userStore.user?.login_email || 
        lb.caller === userStore.user?.login_email
      )
    )
  }
  return betsStore.liveBets
})

function getUserPosition(bet) {
  const userEmail = userStore.user?.login_email
  const liveBet = bet.live_bets.find(lb => 
    lb.bettor === userEmail || lb.caller === userEmail
  )
  if (!liveBet) return 'N/A'
  return liveBet.bettor === userEmail ? 'Blue Team' : 'Red Team'
}

function getUserAmount(bet) {
  const userEmail = userStore.user?.login_email
  const liveBet = bet.live_bets.find(lb => 
    lb.bettor === userEmail || lb.caller === userEmail
  )
  return liveBet ? liveBet.bet_amount : 0
}

onMounted(() => {
  betsStore.fetchRecentBets()
})
</script>

<style scoped>
.live-bets-view {
  padding: 1rem;
}

.filter-info {
  padding: 0.5rem;
  background: rgba(0, 0, 0, 0.05);
  border-radius: 8px;
  margin-bottom: 1rem;
}

.empty-state {
  text-align: center;
  padding: 3rem;
  color: #999;
}

.bets-grid {
  display: grid;
  gap: 1rem;
}

.live-bet-card {
  background: white;
  border-radius: 12px;
  padding: 1.5rem;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  position: relative;
  border: 2px solid #4caf50;
}

.live-indicator {
  position: absolute;
  top: 1rem;
  right: 1rem;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  color: #4caf50;
  font-weight: bold;
  font-size: 0.9rem;
}

.pulse {
  width: 8px;
  height: 8px;
  background: #4caf50;
  border-radius: 50%;
  animation: pulse 2s infinite;
}

@keyframes pulse {
  0% {
    box-shadow: 0 0 0 0 rgba(76, 175, 80, 0.7);
  }
  70% {
    box-shadow: 0 0 0 10px rgba(76, 175, 80, 0);
  }
  100% {
    box-shadow: 0 0 0 0 rgba(76, 175, 80, 0);
  }
}

.bet-matchup {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin: 1.5rem 0;
  padding: 1rem;
  background: #f5f5f5;
  border-radius: 8px;
}

.team-section {
  display: flex;
  flex-direction: column;
  align-items: center;
  flex: 1;
}

.team-name {
  font-weight: bold;
  margin-bottom: 0.5rem;
}

.team-score {
  font-size: 1.5rem;
  font-weight: bold;
  color: #333;
}

.vs {
  padding: 0 1rem;
  color: #999;
  font-weight: bold;
}

.bet-info {
  margin-bottom: 1.5rem;
}

.info-row {
  display: flex;
  justify-content: space-between;
  padding: 0.5rem 0;
  border-bottom: 1px solid #eee;
}

.info-row:last-child {
  border-bottom: none;
}

.position {
  font-weight: bold;
  color: #2196f3;
}

.bet-participants {
  background: #f9f9f9;
  padding: 1rem;
  border-radius: 8px;
}

.bet-participants h4 {
  margin-bottom: 0.75rem;
  color: #333;
}

.participants-list {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.participant {
  display: flex;
  justify-content: space-between;
  padding: 0.5rem;
  background: white;
  border-radius: 4px;
  font-size: 0.9rem;
}
</style>

// src/views/BetStuff/LiveBetsView.jsx
import { useEffect, useMemo } from 'react'
import { useNavigationStore } from '@/store/navigationStore'
import { useBetsStore } from '@/store/betsStore'
import { useUserStore } from '@/store/userStore'
import LoadingSpinner from '@/components/common/LoadingSpinner'

function LiveBetsView() {
  const { currentFilter } = useNavigationStore()
  const { isLoading, getLiveBets, fetchRecentBets } = useBetsStore()
  const { user } = useUserStore()

  const liveBets = getLiveBets()

  const filteredBets = useMemo(() => {
    if (currentFilter === 'Mine') {
      return liveBets.filter(bet =>
        bet.live_bets?.some(lb =>
          lb.bettor === user?.login_email ||
          lb.caller === user?.login_email
        )
      )
    }
    return liveBets
  }, [liveBets, currentFilter, user])

  const getUserPosition = (bet) => {
    const userEmail = user?.login_email
    const liveBet = bet.live_bets?.find(lb =>
      lb.bettor === userEmail || lb.caller === userEmail
    )
    if (!liveBet) return 'N/A'
    return liveBet.bettor === userEmail ? 'Blue Team' : 'Red Team'
  }

  const getUserAmount = (bet) => {
    const userEmail = user?.login_email
    const liveBet = bet.live_bets?.find(lb =>
      lb.bettor === userEmail || lb.caller === userEmail
    )
    return liveBet ? liveBet.bet_amount : 0
  }

  useEffect(() => {
    fetchRecentBets()
  }, [fetchRecentBets])

  return (
    <div className="p-4">
      <h2 className="text-2xl font-bold mb-4">Live Bets</h2>
      {currentFilter && (
        <div className="p-2 bg-black/5 rounded-lg mb-4">
          Showing: {currentFilter}
        </div>
      )}

      {isLoading ? (
        <LoadingSpinner />
      ) : filteredBets.length === 0 ? (
        <div className="text-center p-12 text-gray-400">
          <p>No live bets at the moment</p>
        </div>
      ) : (
        <div className="grid gap-4">
          {filteredBets.map((bet) => (
            <div
              key={bet.bet_id}
              className="bg-white rounded-xl p-6 shadow-md relative border-2 border-green-500"
            >
              <div className="absolute top-4 right-4 flex items-center gap-2 text-green-500 font-bold text-sm">
                <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
                LIVE
              </div>

              <div className="flex items-center justify-between my-6 p-4 bg-gray-100 rounded-lg">
                <div className="flex flex-col items-center flex-1">
                  <span className="font-bold mb-2">{Object.keys(bet.blue_team || {})[0]}</span>
                  <span className="text-2xl font-bold text-gray-800">
                    {Object.values(bet.blue_team || {})[0]}
                  </span>
                </div>
                <div className="px-4 text-gray-400 font-bold">VS</div>
                <div className="flex flex-col items-center flex-1">
                  <span className="font-bold mb-2">{Object.keys(bet.red_team || {})[0]}</span>
                  <span className="text-2xl font-bold text-gray-800">
                    {Object.values(bet.red_team || {})[0]}
                  </span>
                </div>
              </div>

              <div className="mb-6">
                <div className="flex justify-between py-2 border-b border-gray-100">
                  <span>Spread:</span>
                  <span>{bet.spread}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-100">
                  <span>Your Position:</span>
                  <span className="font-bold text-blue-500">{getUserPosition(bet)}</span>
                </div>
                <div className="flex justify-between py-2">
                  <span>Amount:</span>
                  <span>${getUserAmount(bet)}</span>
                </div>
              </div>

              <div className="bg-gray-50 p-4 rounded-lg">
                <h4 className="mb-3 text-gray-800 font-semibold">Participants</h4>
                <div className="flex flex-col gap-2">
                  {bet.live_bets?.map((liveBet, idx) => (
                    <div
                      key={idx}
                      className="flex justify-between p-2 bg-white rounded text-sm"
                    >
                      <span>{liveBet.bettor} vs {liveBet.caller}</span>
                      <span>${liveBet.bet_amount}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

export default LiveBetsView
