// src/views/MyStuff/AccountView.vue
<template>
  <div class="account-view">
    <h2>Account Settings</h2>
    
    <div v-if="navigationStore.currentFilter === 'Profile'" class="profile-section">
      <div class="profile-card">
        <div class="avatar">
          <img :src="userStore.user?.display_icon_path || '/default-avatar.png'" alt="Profile">
        </div>
        <div class="profile-info">
          <h3>{{ userStore.displayName || 'User' }}</h3>
          <p>{{ userStore.user?.login_email }}</p>
        </div>
      </div>
      
      <div class="stats-grid">
        <div class="stat-card">
          <span class="stat-value">{{ totalBets }}</span>
          <span class="stat-label">Total Bets</span>
        </div>
        <div class="stat-card">
          <span class="stat-value">{{ winRate }}%</span>
          <span class="stat-label">Win Rate</span>
        </div>
        <div class="stat-card">
          <span class="stat-value">{{ activeBets }}</span>
          <span class="stat-label">Active</span>
        </div>
      </div>
    </div>
    
    <div v-else-if="navigationStore.currentFilter === 'Settings'" class="settings-section">
      <div class="setting-group">
        <h3>Security</h3>
        <button @click="showPasswordModal = true" class="btn btn-primary">
          Change Password
        </button>
      </div>
      
      <div class="setting-group">
        <h3>Preferences</h3>
        <div class="preference-item">
          <label>
            <input type="checkbox" v-model="notifications">
            Enable Notifications
          </label>
        </div>
        <div class="preference-item">
          <label>
            <input type="checkbox" v-model="darkMode">
            Dark Mode
          </label>
        </div>
      </div>
      
      <div class="setting-group">
        <button @click="handleLogout" class="btn btn-danger">
          Logout
        </button>
      </div>
    </div>
    
    <!-- Password Change Modal -->
    <div v-if="showPasswordModal" class="modal-overlay" @click.self="showPasswordModal = false">
      <div class="modal">
        <h3>Change Password</h3>
        <form @submit.prevent="handlePasswordChange">
          <input 
            type="password" 
            v-model="currentPassword" 
            placeholder="Current Password"
            required
          >
          <input 
            type="password" 
            v-model="newPassword" 
            placeholder="New Password"
            required
          >
          <input 
            type="password" 
            v-model="confirmPassword" 
            placeholder="Confirm New Password"
            required
          >
          <div class="modal-actions">
            <button type="button" @click="showPasswordModal = false" class="btn btn-secondary">
              Cancel
            </button>
            <button type="submit" class="btn btn-primary">
              Change Password
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useNavigationStore } from '@/stores/navigation'
import { useUserStore } from '@/stores/user'
import { useBetsStore } from '@/stores/bets'
import { useRouter } from 'vue-router'

const navigationStore = useNavigationStore()
const userStore = useUserStore()
const betsStore = useBetsStore()
const router = useRouter()

const showPasswordModal = ref(false)
const currentPassword = ref('')
const newPassword = ref('')
const confirmPassword = ref('')
const notifications = ref(true)
const darkMode = ref(false)

const totalBets = computed(() => betsStore.bets.length)
const activeBets = computed(() => betsStore.openBets.length + betsStore.liveBets.length)
const winRate = computed(() => {
  // Calculate win rate logic here
  return 65
})

async function handlePasswordChange() {
  if (newPassword.value !== confirmPassword.value) {
    alert('Passwords do not match')
    return
  }
  
  const success = await userStore.changePassword(currentPassword.value, newPassword.value)
  if (success) {
    showPasswordModal.value = false
    currentPassword.value = ''
    newPassword.value = ''
    confirmPassword.value = ''
    alert('Password changed successfully')
  }
}

async function handleLogout() {
  if (confirm('Are you sure you want to logout?')) {
    await userStore.logout()
    router.push('/login')
  }
}
</script>

<style scoped>
.account-view {
  padding: 1rem;
}

.profile-card {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 1.5rem;
  background: white;
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  margin-bottom: 1.5rem;
}

.avatar {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  overflow: hidden;
  border: 3px solid #ddd;
}

.avatar img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.stat-card {
  background: white;
  padding: 1rem;
  border-radius: 8px;
  text-align: center;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.stat-value {
  display: block;
  font-size: 1.5rem;
  font-weight: bold;
  color: #333;
}

.stat-label {
  display: block;
  font-size: 0.8rem;
  color: #666;
  margin-top: 0.25rem;
}

.setting-group {
  background: white;
  padding: 1.5rem;
  border-radius: 8px;
  margin-bottom: 1rem;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.setting-group h3 {
  margin-bottom: 1rem;
  color: #333;
}

.preference-item {
  padding: 0.5rem 0;
}

.preference-item label {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  cursor: pointer;
}

.btn {
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 8px;
  font-size: 1rem;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-primary {
  background: #808080;
  color: white;
}

.btn-secondary {
  background: #ccc;
  color: #333;
}

.btn-danger {
  background: #f44336;
  color: white;
}

.btn:hover {
  opacity: 0.9;
  transform: translateY(-1px);
}

.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.modal {
  background: white;
  padding: 2rem;
  border-radius: 12px;
  width: 90%;
  max-width: 400px;
}

.modal h3 {
  margin-bottom: 1.5rem;
}

.modal input {
  width: 100%;
  padding: 0.75rem;
  margin-bottom: 1rem;
  border: 1px solid #ddd;
  border-radius: 8px;
  font-size: 1rem;
}

.modal-actions {
  display: flex;
  gap: 1rem;
  justify-content: flex-end;
  margin-top: 1.5rem;
}
</style>

// src/views/MyStuff/AccountView.jsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useNavigationStore } from '@/store/navigationStore'
import { useUserStore } from '@/store/userStore'
import { useBetsStore } from '@/store/betsStore'

function AccountView() {
  const navigate = useNavigate()
  const { currentFilter } = useNavigationStore()
  const { user, getDisplayName, changePassword, logout } = useUserStore()
  const { bets, getOpenBets, getLiveBets } = useBetsStore()

  const [showPasswordModal, setShowPasswordModal] = useState(false)
  const [currentPassword, setCurrentPassword] = useState('')
  const [newPassword, setNewPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [notifications, setNotifications] = useState(true)
  const [darkMode, setDarkMode] = useState(false)

  const totalBets = bets.length
  const activeBets = getOpenBets().length + getLiveBets().length
  const winRate = 65

  const handlePasswordChange = async (e) => {
    e.preventDefault()
    if (newPassword !== confirmPassword) {
      alert('Passwords do not match')
      return
    }

    const success = await changePassword(currentPassword, newPassword)
    if (success) {
      setShowPasswordModal(false)
      setCurrentPassword('')
      setNewPassword('')
      setConfirmPassword('')
      alert('Password changed successfully')
    }
  }

  const handleLogout = async () => {
    if (window.confirm('Are you sure you want to logout?')) {
      logout()
      navigate('/login')
    }
  }

  return (
    <div className="p-4">
      <h2 className="text-2xl font-bold mb-4">Account Settings</h2>

      {currentFilter === 'Profile' && (
        <div>
          <div className="flex items-center gap-4 p-6 bg-white rounded-xl shadow-md mb-6">
            <div className="w-20 h-20 rounded-full overflow-hidden border-[3px] border-gray-200">
              <img
                src={user?.display_icon_path || '/default-avatar.png'}
                alt="Profile"
                className="w-full h-full object-cover"
              />
            </div>
            <div>
              <h3 className="text-xl font-semibold">{getDisplayName() || 'User'}</h3>
              <p className="text-gray-600">{user?.login_email}</p>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-4 mb-6">
            <div className="bg-white p-4 rounded-lg text-center shadow-sm">
              <span className="block text-2xl font-bold text-gray-800">{totalBets}</span>
              <span className="block text-sm text-gray-600 mt-1">Total Bets</span>
            </div>
            <div className="bg-white p-4 rounded-lg text-center shadow-sm">
              <span className="block text-2xl font-bold text-gray-800">{winRate}%</span>
              <span className="block text-sm text-gray-600 mt-1">Win Rate</span>
            </div>
            <div className="bg-white p-4 rounded-lg text-center shadow-sm">
              <span className="block text-2xl font-bold text-gray-800">{activeBets}</span>
              <span className="block text-sm text-gray-600 mt-1">Active</span>
            </div>
          </div>
        </div>
      )}

      {currentFilter === 'Settings' && (
        <div>
          <div className="bg-white p-6 rounded-lg mb-4 shadow-sm">
            <h3 className="mb-4 text-gray-800 font-semibold">Security</h3>
            <button
              onClick={() => setShowPasswordModal(true)}
              className="px-6 py-3 bg-gray-500 text-white rounded-lg border-none cursor-pointer transition-all hover:opacity-90 hover:-translate-y-px"
            >
              Change Password
            </button>
          </div>

          <div className="bg-white p-6 rounded-lg mb-4 shadow-sm">
            <h3 className="mb-4 text-gray-800 font-semibold">Preferences</h3>
            <div className="py-2">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={notifications}
                  onChange={(e) => setNotifications(e.target.checked)}
                />
                Enable Notifications
              </label>
            </div>
            <div className="py-2">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={darkMode}
                  onChange={(e) => setDarkMode(e.target.checked)}
                />
                Dark Mode
              </label>
            </div>
          </div>

          <div className="bg-white p-6 rounded-lg shadow-sm">
            <button
              onClick={handleLogout}
              className="px-6 py-3 bg-red-500 text-white rounded-lg border-none cursor-pointer transition-all hover:opacity-90 hover:-translate-y-px"
            >
              Logout
            </button>
          </div>
        </div>
      )}

      {showPasswordModal && (
        <div
          className="fixed inset-0 bg-black/50 flex items-center justify-center z-[1000]"
          onClick={(e) => e.target === e.currentTarget && setShowPasswordModal(false)}
        >
          <div className="bg-white p-8 rounded-xl w-[90%] max-w-[400px]">
            <h3 className="mb-6 text-xl font-semibold">Change Password</h3>
            <form onSubmit={handlePasswordChange}>
              <input
                type="password"
                value={currentPassword}
                onChange={(e) => setCurrentPassword(e.target.value)}
                placeholder="Current Password"
                required
                className="w-full p-3 mb-4 border border-gray-200 rounded-lg text-base"
              />
              <input
                type="password"
                value={newPassword}
                onChange={(e) => setNewPassword(e.target.value)}
                placeholder="New Password"
                required
                className="w-full p-3 mb-4 border border-gray-200 rounded-lg text-base"
              />
              <input
                type="password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                placeholder="Confirm New Password"
                required
                className="w-full p-3 mb-4 border border-gray-200 rounded-lg text-base"
              />
              <div className="flex gap-4 justify-end mt-6">
                <button
                  type="button"
                  onClick={() => setShowPasswordModal(false)}
                  className="px-6 py-3 bg-gray-300 text-gray-800 rounded-lg border-none cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-6 py-3 bg-gray-500 text-white rounded-lg border-none cursor-pointer"
                >
                  Change Password
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}

export default AccountView
