// src/views/MyStuff/HistoryView.vue
<template>
  <div class="history-view">
    <h2>Betting History</h2>
    <div v-if="navigationStore.currentFilter" class="filter-info">
      Showing: {{ navigationStore.currentFilter }} History
    </div>
    
    <div class="history-controls">
      <select v-model="selectedPeriod" class="period-select">
        <option value="all">All Time</option>
        <option value="month">Last Month</option>
        <option value="week">Last Week</option>
        <option value="today">Today</option>
      </select>
      
      <select v-model="selectedType" class="type-select">
        <option value="all">All Types</option>
        <option value="won">Won</option>
        <option value="lost">Lost</option>
        <option value="cancelled">Cancelled</option>
      </select>
    </div>
    
    <div class="history-list">
      <div v-for="bet in filteredHistory" :key="bet.bet_id" class="history-item">
        <div class="history-header">
          <span class="bet-date">{{ formatDate(bet.decision_timestamp) }}</span>
          <span class="bet-status" :class="getStatusClass(bet.status)">
            {{ bet.status }}
          </span>
        </div>
        
        <div class="history-body">
          <div class="teams">
            {{ Object.keys(bet.blue_team)[0] }} vs {{ Object.keys(bet.red_team)[0] }}
          </div>
          <div class="bet-details">
            <span>Spread: {{ bet.spread }}</span>
            <span class="result" :class="getResultClass(bet)">
              {{ getResult(bet) }}
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useNavigationStore } from '@/stores/navigation'
import { useBetsStore } from '@/stores/bets'
import { useUserStore } from '@/stores/user'

const navigationStore = useNavigationStore()
const betsStore = useBetsStore()
const userStore = useUserStore()

const selectedPeriod = ref('all')
const selectedType = ref('all')

const filteredHistory = computed(() => {
  let bets = betsStore.doneBets
  
  if (navigationStore.currentFilter === 'Me') {
    bets = bets.filter(bet => 
      bet.created_by === userStore.user?.login_email ||
      bet.decided_bets.some(db => 
        db.bettor === userStore.user?.login_email || 
        db.caller === userStore.user?.login_email
      )
    )
  }
  
  // Apply period filter
  if (selectedPeriod.value !== 'all') {
    // Filter logic based on period
  }
  
  // Apply type filter
  if (selectedType.value !== 'all') {
    // Filter logic based on type
  }
  
  return bets
})

function formatDate(timestamp) {
  return new Date(timestamp * 1000).toLocaleDateString()
}

function getStatusClass(status) {
  return status.toLowerCase()
}

function getResult(bet) {
  // Calculate win/loss amount
  return '+$50'
}

function getResultClass(bet) {
  return 'win' // or 'loss'
}
</script>

<style scoped>
.history-view {
  padding: 1rem;
}

.history-controls {
  display: flex;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.period-select,
.type-select {
  flex: 1;
  padding: 0.75rem;
  border: 1px solid #ddd;
  border-radius: 8px;
  background: white;
  font-size: 1rem;
}

.history-list {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.history-item {
  background: white;
  border-radius: 12px;
  padding: 1.5rem;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.history-header {
  display: flex;
  justify-content: space-between;
  margin-bottom: 1rem;
}

.bet-date {
  color: #666;
  font-size: 0.9rem;
}

.bet-status {
  padding: 0.25rem 0.75rem;
  border-radius: 20px;
  font-size: 0.85rem;
  font-weight: 600;
}

.bet-status.decided {
  background: #e3f2fd;
  color: #1976d2;
}

.bet-status.expired {
  background: #fff3e0;
  color: #f57c00;
}

.bet-status.cancelled {
  background: #ffebee;
  color: #d32f2f;
}

.teams {
  font-weight: 600;
  margin-bottom: 0.5rem;
}

.bet-details {
  display: flex;
  justify-content: space-between;
  color: #666;
}

.result {
  font-weight: bold;
}

.result.win {
  color: #4caf50;
}

.result.loss {
  color: #f44336;
}
</style>

// src/views/MyStuff/HistoryView.jsx
import { useState, useMemo } from 'react'
import { useNavigationStore } from '@/store/navigationStore'
import { useBetsStore } from '@/store/betsStore'
import { useUserStore } from '@/store/userStore'

function HistoryView() {
  const { currentFilter } = useNavigationStore()
  const { getDoneBets } = useBetsStore()
  const { user } = useUserStore()

  const [selectedPeriod, setSelectedPeriod] = useState('all')
  const [selectedType, setSelectedType] = useState('all')

  const doneBets = getDoneBets()

  const filteredHistory = useMemo(() => {
    let bets = doneBets

    if (currentFilter === 'Me') {
      bets = bets.filter(bet =>
        bet.created_by === user?.login_email ||
        bet.decided_bets?.some(db =>
          db.bettor === user?.login_email ||
          db.caller === user?.login_email
        )
      )
    }

    // Apply period and type filters here if needed

    return bets
  }, [doneBets, currentFilter, user, selectedPeriod, selectedType])

  const formatDate = (timestamp) => {
    return new Date(timestamp * 1000).toLocaleDateString()
  }

  const getStatusClass = (status) => {
    switch (status.toLowerCase()) {
      case 'decided':
        return 'bg-blue-100 text-blue-700'
      case 'expired':
        return 'bg-orange-100 text-orange-700'
      case 'cancelled':
        return 'bg-red-100 text-red-700'
      default:
        return 'bg-gray-100 text-gray-700'
    }
  }

  const getResult = (bet) => {
    return '+$50'
  }

  const getResultClass = (bet) => {
    return 'text-green-500'
  }

  return (
    <div className="p-4">
      <h2 className="text-2xl font-bold mb-4">Betting History</h2>
      {currentFilter && (
        <div className="p-2 bg-black/5 rounded-lg mb-4">
          Showing: {currentFilter} History
        </div>
      )}

      <div className="flex gap-4 mb-6">
        <select
          value={selectedPeriod}
          onChange={(e) => setSelectedPeriod(e.target.value)}
          className="flex-1 p-3 border border-gray-200 rounded-lg bg-white text-base"
        >
          <option value="all">All Time</option>
          <option value="month">Last Month</option>
          <option value="week">Last Week</option>
          <option value="today">Today</option>
        </select>

        <select
          value={selectedType}
          onChange={(e) => setSelectedType(e.target.value)}
          className="flex-1 p-3 border border-gray-200 rounded-lg bg-white text-base"
        >
          <option value="all">All Types</option>
          <option value="won">Won</option>
          <option value="lost">Lost</option>
          <option value="cancelled">Cancelled</option>
        </select>
      </div>

      <div className="flex flex-col gap-4">
        {filteredHistory.map((bet) => (
          <div key={bet.bet_id} className="bg-white rounded-xl p-6 shadow-md">
            <div className="flex justify-between mb-4">
              <span className="text-gray-600 text-sm">{formatDate(bet.decision_timestamp)}</span>
              <span className={`px-3 py-1 rounded-full text-sm font-semibold ${getStatusClass(bet.status)}`}>
                {bet.status}
              </span>
            </div>

            <div className="font-semibold mb-2">
              {Object.keys(bet.blue_team || {})[0]} vs {Object.keys(bet.red_team || {})[0]}
            </div>

            <div className="flex justify-between text-gray-600">
              <span>Spread: {bet.spread}</span>
              <span className={`font-bold ${getResultClass(bet)}`}>
                {getResult(bet)}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export default HistoryView
