// src/views/LeagueStuff/ChatsView.jsx
import { useState } from 'react'
import { useNavigationStore } from '@/store/navigationStore'
import { useUserStore } from '@/store/userStore'

function ChatsView() {
  const { currentFilter } = useNavigationStore()
  const { getDisplayName } = useUserStore()

  const [newMessage, setNewMessage] = useState('')
  const [messages, setMessages] = useState([
    { id: 1, user: 'Player123', content: "Anyone want to bet on tonight's game?", timestamp: new Date() },
    { id: 2, user: 'BetMaster', content: "I'm in! What's the spread?", timestamp: new Date() },
    { id: 3, user: 'LuckyOne', content: 'Count me in too', timestamp: new Date() }
  ])

  const sendMessage = () => {
    if (newMessage.trim()) {
      setMessages([
        ...messages,
        {
          id: messages.length + 1,
          user: getDisplayName() || 'You',
          content: newMessage,
          timestamp: new Date()
        }
      ])
      setNewMessage('')
    }
  }

  const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      sendMessage()
    }
  }

  const formatTime = (timestamp) => {
    return new Intl.DateTimeFormat('en-US', {
      hour: 'numeric',
      minute: 'numeric',
      hour12: true
    }).format(timestamp)
  }

  return (
    <div className="p-4 h-full flex flex-col">
      <h2 className="text-2xl font-bold mb-4">League Chats</h2>
      {currentFilter && (
        <div className="p-2 bg-black/5 rounded-lg mb-4">
          Channel: {currentFilter}
        </div>
      )}

      <div className="flex-1 bg-white rounded-xl shadow-md flex flex-col overflow-hidden">
        <div className="flex-1 p-4 overflow-y-auto flex flex-col gap-4">
          {messages.map((message) => (
            <div key={message.id} className="bg-gray-50 p-3 rounded-lg">
              <div className="flex justify-between mb-2">
                <span className="font-semibold text-gray-800">{message.user}</span>
                <span className="text-xs text-gray-400">{formatTime(message.timestamp)}</span>
              </div>
              <div className="text-gray-600">{message.content}</div>
            </div>
          ))}
        </div>

        <div className="flex p-4 border-t border-gray-100 gap-2">
          <input
            type="text"
            value={newMessage}
            onChange={(e) => setNewMessage(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder="Type a message..."
            className="flex-1 p-3 border border-gray-200 rounded-lg text-base"
          />
          <button
            onClick={sendMessage}
            className="px-6 py-3 bg-gray-500 text-white rounded-lg border-none cursor-pointer transition-colors hover:bg-gray-600"
          >
            Send
          </button>
        </div>
      </div>
    </div>
  )
}

export default ChatsView

// src/views/LeagueStuff/ChatsView.vue
<template>
  <div class="chats-view">
    <h2>League Chats</h2>
    <div v-if="navigationStore.currentFilter" class="filter-info">
      Channel: {{ navigationStore.currentFilter }}
    </div>
    
    <div class="chat-container">
      <div class="messages-area">
        <div v-for="message in messages" :key="message.id" class="message">
          <div class="message-header">
            <span class="username">{{ message.user }}</span>
            <span class="timestamp">{{ formatTime(message.timestamp) }}</span>
          </div>
          <div class="message-content">{{ message.content }}</div>
        </div>
      </div>
      
      <div class="chat-input">
        <input 
          v-model="newMessage" 
          @keyup.enter="sendMessage"
          placeholder="Type a message..."
        >
        <button @click="sendMessage" class="send-btn">Send</button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useNavigationStore } from '@/stores/navigation'
import { useUserStore } from '@/stores/user'

const navigationStore = useNavigationStore()
const userStore = useUserStore()

const newMessage = ref('')
const messages = ref([
  { id: 1, user: 'Player123', content: 'Anyone want to bet on tonight\'s game?', timestamp: new Date() },
  { id: 2, user: 'BetMaster', content: 'I\'m in! What\'s the spread?', timestamp: new Date() },
  { id: 3, user: 'LuckyOne', content: 'Count me in too', timestamp: new Date() }
])

function sendMessage() {
  if (newMessage.value.trim()) {
    messages.value.push({
      id: messages.value.length + 1,
      user: userStore.displayName || 'You',
      content: newMessage.value,
      timestamp: new Date()
    })
    newMessage.value = ''
  }
}

function formatTime(timestamp) {
  return new Intl.DateTimeFormat('en-US', {
    hour: 'numeric',
    minute: 'numeric',
    hour12: true
  }).format(timestamp)
}
</script>

<style scoped>
.chats-view {
  padding: 1rem;
  height: 100%;
  display: flex;
  flex-direction: column;
}

.chat-container {
  flex: 1;
  background: white;
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.messages-area {
  flex: 1;
  padding: 1rem;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.message {
  background: #f9f9f9;
  padding: 0.75rem;
  border-radius: 8px;
}

.message-header {
  display: flex;
  justify-content: space-between;
  margin-bottom: 0.5rem;
}

.username {
  font-weight: 600;
  color: #333;
}

.timestamp {
  font-size: 0.8rem;
  color: #999;
}

.message-content {
  color: #666;
}

.chat-input {
  display: flex;
  padding: 1rem;
  border-top: 1px solid #eee;
  gap: 0.5rem;
}

.chat-input input {
  flex: 1;
  padding: 0.75rem;
  border: 1px solid #ddd;
  border-radius: 8px;
  font-size: 1rem;
}

.send-btn {
  padding: 0.75rem 1.5rem;
  background: #808080;
  color: white;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s;
}

.send-btn:hover {
  background: #666;
}
</style>
