// src/components/layout/AppNavigation.vue
<template>
  <nav class="navigation" :class="{ 'navigation-portrait': isPortrait, 'navigation-landscape': !isPortrait }">
    <!-- Filter buttons area - shown above main/sub buttons -->
    <FilterButtons v-if="navigationStore.availableFilters.length > 0" class="nav-filter-section" />

    <!-- Main/Sub buttons area -->
    <div class="navigation-container">
      <template v-for="section in navigationStore.navSections" :key="section.id">
        <!-- Main button - only visible when showMainButton is true or when this section is not active -->
        <MainButton
          v-if="navigationStore.showMainButton || navigationStore.activeMainButton !== section.name"
          :section="section"
          :is-active="navigationStore.activeMainButton === section.name"
          :is-collapsed="navigationStore.activeMainButton && navigationStore.activeMainButton !== section.name && !navigationStore.showMainButton"
          @click="handleMainClick(section)"
        />

        <!-- Sub buttons - visible when this section is active and main button is hidden -->
        <template v-if="navigationStore.activeMainButton === section.name && !navigationStore.showMainButton">
          <SubButton
            v-for="subButton in section.subButtons"
            :key="subButton.name"
            :sub-button="subButton"
            :section-name="section.name"
            :is-active="navigationStore.currentSubButton === subButton.name"
            @click="handleSubClick(section.name, subButton)"
          />
        </template>
      </template>
    </div>
  </nav>
</template>

<script setup>
import { computed } from 'vue'
import { useNavigationStore } from '@/stores/navigation'
import { useRouter } from 'vue-router'
import MainButton from '@/components/navigation/MainButton.vue'
import SubButton from '@/components/navigation/SubButton.vue'
import FilterButtons from '@/components/navigation/FilterButtons.vue'

const navigationStore = useNavigationStore()
const router = useRouter()

const isPortrait = computed(() => navigationStore.isPortrait)

function handleMainClick(section) {
  const expanded = navigationStore.selectMainButton(section)
  if (expanded && navigationStore.currentSubButton) {
    const sub = section.subButtons.find(s => s.name === navigationStore.currentSubButton)
    if (sub) {
      router.push(`${section.path}/${sub.path}`)
    }
  }
}

function handleSubClick(sectionName, subButton) {
  // If clicking the already active sub button, return to main view
  if (navigationStore.currentSubButton === subButton.name) {
    navigationStore.returnToMainView()
    const section = navigationStore.navSections.find(s => s.name === sectionName)
    if (section) {
      router.push(section.path) // Navigate to main section page
    }
  } else {
    // Select the sub button normally
    navigationStore.selectSubButton(sectionName, subButton)
    const section = navigationStore.navSections.find(s => s.name === sectionName)
    if (section) {
      router.push(`${section.path}/${subButton.path}`)
    }
  }
}
</script>

<style scoped>
.navigation {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  position: relative;
  z-index: 100;
  flex-shrink: 0;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

.nav-filter-section {
  flex-shrink: 0;
  border-bottom: 1px solid rgba(255, 255, 255, 0.2);
}

.navigation-container {
  display: flex;
  width: 100%;
  flex: 1;
  min-height: 0;
}

/* Portrait mode - bottom navigation */
.navigation-portrait {
  height: auto;
  min-height: 70px;
  width: 100%;
  border-top: 1px solid rgba(255, 255, 255, 0.2);
  padding-bottom: max(8px, env(safe-area-inset-bottom)); /* Ensure buttons aren't cut off by home indicator */
}

.navigation-portrait.has-filters {
  min-height: 120px; /* Extra height for filter buttons */
}

.navigation-portrait .navigation-container {
  flex-direction: row;
  justify-content: space-between;
  align-items: stretch;
  min-height: 70px;
  max-height: 70px;
}

/* Landscape mode - side navigation */
.navigation-landscape {
  height: 100%;
  width: 15vw;
  min-width: 150px;
  max-width: 200px;
  border-left: 1px solid rgba(255, 255, 255, 0.2);
}

.navigation-landscape .navigation-container {
  flex-direction: column;
  justify-content: flex-start;
}

@media (orientation: portrait) {
  .navigation {
    position: relative;
    bottom: 0;
    left: 0;
    right: 0;
  }
}

@media (orientation: landscape) {
  .navigation {
    position: relative;
    top: 0;
    right: 0;
    bottom: 0;
    order: 2;
  }
  
  @media (max-device-width: 926px) {
    .navigation {
      order: 0;
      border-left: none;
      border-right: 1px solid rgba(255, 255, 255, 0.2);
    }
  }
}

.navigation {
  visibility: visible !important;
  display: flex !important;
}
</style>

// src/components/layout/AppNavigation.jsx
import { useNavigate } from 'react-router-dom'
import { useNavigationStore } from '@/store/navigationStore'
import MainButton from '@/components/navigation/MainButton'
import SubButton from '@/components/navigation/SubButton'
import FilterButtons from '@/components/navigation/FilterButtons'

function AppNavigation() {
  const navigate = useNavigate()
  const {
    isPortrait,
    navSections,
    activeMainButton,
    currentSubButton,
    showMainButton,
    availableFilters,
    selectMainButton,
    selectSubButton,
    returnToMainView
  } = useNavigationStore()

  const handleMainClick = (section) => {
    const expanded = selectMainButton(section)
    const state = useNavigationStore.getState()
    if (expanded && state.currentSubButton) {
      const sub = section.subButtons.find(s => s.name === state.currentSubButton)
      if (sub) {
        navigate(`${section.path}/${sub.path}`)
      }
    }
  }

  const handleSubClick = (sectionName, subButton) => {
    if (currentSubButton === subButton.name) {
      returnToMainView()
      const section = navSections.find(s => s.name === sectionName)
      if (section) {
        navigate(section.path)
      }
    } else {
      selectSubButton(sectionName, subButton)
      const section = navSections.find(s => s.name === sectionName)
      if (section) {
        navigate(`${section.path}/${subButton.path}`)
      }
    }
  }

  return (
    <nav
      className={`backdrop-blur-md relative z-[100] flex-shrink-0 overflow-hidden flex flex-col ${
        isPortrait
          ? 'h-auto min-h-[70px] w-full border-t border-white/20 pb-safe-bottom'
          : 'h-full w-[15vw] min-w-[150px] max-w-[200px] border-l border-white/20'
      }`}
      style={{ paddingBottom: isPortrait ? 'max(8px, env(safe-area-inset-bottom))' : 0 }}
    >
      {availableFilters.length > 0 && (
        <FilterButtons className="flex-shrink-0 border-b border-white/20" />
      )}

      <div
        className={`flex w-full flex-1 min-h-0 ${
          isPortrait
            ? 'flex-row justify-between items-stretch min-h-[70px] max-h-[70px]'
            : 'flex-col justify-start'
        }`}
      >
        {navSections.map((section) => (
          <div key={section.id} className="contents">
            {(showMainButton || activeMainButton !== section.name) && (
              <MainButton
                section={section}
                isActive={activeMainButton === section.name}
                isCollapsed={activeMainButton && activeMainButton !== section.name && !showMainButton}
                onClick={() => handleMainClick(section)}
              />
            )}

            {activeMainButton === section.name && !showMainButton && (
              section.subButtons.map((subButton) => (
                <SubButton
                  key={subButton.name}
                  subButton={subButton}
                  sectionName={section.name}
                  isActive={currentSubButton === subButton.name}
                  onClick={() => handleSubClick(section.name, subButton)}
                />
              ))
            )}
          </div>
        ))}
      </div>
    </nav>
  )
}

export default AppNavigation
